### PR TITLE
Feature/costmap 2d separation

### PR DESCRIPTION
**Pull request by pfankhauser**
I have separated the costmap_2d conversion functionality into a separate package (#94). This way, users working only with the standard installation of ROS can use `grid_map_ros` without installing `costmap_2d` first.

@stonier: Could you please check if this still works for your projects before I merge? Thanks!

### CODE REVIEW

**Comment by stonier** [comment]
@pfankhauser no longer at Yujin, but I can certainly at least check it keeps working with `cost_map` and it's tests. Will check it on the weekend once I have some cycles.

**Comment by stonier** [comment]
Not forgotten. Just a heads up to say sorry - had a guest arrive last weekend. Rescheduled for this weekend which I have free.

**Comment by stonier** [comment]
Green light here...I have a branch to PR as soon as this goes in.

**Comment by pfankhauser** [comment]
Great, thanks for checking!

**Pull request merged**
